### ISSUE TITLE
where is the file ready_aapl_hour_duska_2018-01-02_2020-12-31.csv?

### ISSUE THREAD

**Issue by lbgitjp** [xicocaio/its-sentarl#2]
when i run the project, it failed to load the file ready_aapl_hour_duska_2018-01-02_2020-12-31.csv, where can i get the file?

thanks!

**Comment by xicocaio** [comment]
HI @lbgitjp 


I just uploaded the file you requested to the master branch, which now contains the necessary data for running this project for the `aapl` asset. Can you please verify if it works for you now?

I did not upload most `.csv` files given that the websites that provide this data allow for free usage but do not allow distribution without their consent.

However, you can gather the exact data I used in my experiments by following the instructions I provided in this repo documentation. For instance, in the [Full Article (ACM)](https://dl.acm.org/doi/10.1145/3490354.3494445), I explain how I collected the price data and grouped it with the news data. In this one [Article](https://www.researchgate.net/publication/339962669_Assessing_Regression-Based_Sentiment_Analysis_Techniques_in_Financial_Texts) you can get the instructions on how to build the news sentiment extractor and here is the  [Source code](https://bit.ly/3kzau8G). Finally to gather the news data you can use my web crawler  [Source code](https://github.com/xicocaio/financial_web_crawler).


Thank you for experimenting with this repo and please, let me know if you have any other issues =)

**Comment by lbgitjp** [comment]
thank you, now i can run it, but when i run \_\_main\_\_.py, it has a error at below position:
https://github.com/xicocaio/its-sentarl/blob/49d8b140c5b5dbeb5e4003bbe1e69ebf8cb3db10/app/envs/stock.py#L233-L237

![pic](https://user-images.githubusercontent.com/43297325/200273312-10278781-02de-47d0-8372-9a1f32cf4ac7.png)

should i set some arguments to let it run?

thanks!

**Comment by xicocaio** [comment]
Hi @lbgitjp ,

The easiest way to test the system is to just open a terminal or command prompt and execute the command `python app` inside the `its-sentarl` folder. Also, you should have initialized the virtual environment using `pipenv shell`.

How are you trying to run the system?

**Comment by lbgitjp** [comment]
only after change below code:
https://github.com/xicocaio/its-sentarl/blob/49d8b140c5b5dbeb5e4003bbe1e69ebf8cb3db10/app/setups/base_setup.py#L72-L74

to:
```
    action, _states = model.predict(
        observation, deterministic=self.config.deterministic_test
    )
    action = action[()]
```
then it can work, otherwise train_model can work, but "test" can't work.

thanks!
