### ISSUE TITLE
The Sentiment extractor module is no longer valid

### ISSUE THREAD

**Issue by carrot0117** [xicocaio/its-sentarl#3]
The link to the source code of the Sentiment extractor module is no longer valid. Can a new link be added. Thanks!

**Comment by xicocaio** [comment]
> The link to the source code of the Sentiment extractor module is no longer valid. Can a new link be added. Thanks!

I will upload a fix, but for now, you can use this link: http://bit.ly/4gavU8u

Thanks for the heads up

**Comment by carrot0117** [comment]
It works! Thank you for answering my question. Your help is much appreciated!
